import 'package:google_fonts/google_fonts.dart';

///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Res {
  Res._();

  static String appFontFamily = GoogleFonts.cairo().fontFamily ?? '';

  //========================== Api Endpoints  ===============================
  static const apiLogin = 'auth/login';
  static const apiLogout = 'auth/logout';
  static const apiRegister = 'auth/register';
  static const apiProfile = 'auth/profile';

  //========================== Animation Assets  ===============================
  static const animApiLoading = 'assets/anim/api_loading.json';
  static const animApiEmpty = 'assets/anim/api_empty.json';
  static const animApiError = 'assets/anim/api_error.json';
  static const animSuccess = 'assets/anim/success.json';
  static const animDisconnect = 'assets/anim/disconnect.json';

  //========================== Icons Assets  ===============================
  static const String iconPhone = 'assets/icons/phone.svg';
  static const String iconEmail = 'assets/icons/email.svg';
  static const String iconPassword = 'assets/icons/password.svg';

  static const String iconMale = 'assets/icons/male.svg';
  static const String iconFemale = 'assets/icons/female.svg';
  static const String iconLogo = 'assets/icons/logo.svg';
  static const String iconNotification = 'assets/icons/notification.svg';
  static const String iconDrawerLogo = 'assets/icons/drawer_logo.svg';
  static const String iconHome = 'assets/icons/home.svg';
  static const String iconProfile = 'assets/icons/profile.svg';
  static const String iconLanguage = 'assets/icons/language.svg';
  static const String iconSubjects = 'assets/icons/subjects.svg';
  static const String iconAbout = 'assets/icons/about.svg';
  static const String iconSignOut = 'assets/icons/signout.svg';
  static const String iconClock = 'assets/icons/clock.svg';
  static const String iconEdit = 'assets/icons/edit.svg';

  //========================== Images Assets  ===============================
  static const logoImage = "assets/images/launcher/logo.png";
  static const logoWhiteImage = "assets/images/launcher/logo_white.png";
}
